language: ruby
rvm:
  - 2.1.0-dev
  - 2.0.0-p247
  - 1.9.3
  - 1.9.2
  - 1.9.1
  - 1.8.7
  - 1.8.6
install:
  - wget -O - https://github.com/git/git/archive/v${GIT_VERSION}.tar.gz && tar xvf -
  - ls
evn:
  - ignore=this
matrix:
  exclude:
    - env: ignore=this
  include:
    - env: GIT_VERSION=1.8.4
    - env: GIT_VERSION=1.8.3
    - env: GIT_VERSION=1.8.2
    - env: GIT_VERSION=1.8.1
    - env: GIT_VERSION=1.8.0
    - env: GIT_VERSION=1.7.0
    - env: GIT_VERSION=1.6.0
    - env: GIT_VERSION=1.5.0
    - env: GIT_VERSION=1.4.0
    - env: GIT_VERSION=1.3.0

