language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.9.1
  - 1.8.7
  - 1.8.6
before_install:
  - mkdir -p ~/local/src
  - pushd `pwd`
  - cd ~/local/src
  - for version in ${GIT_VERSIONS}; do
      echo install git-${GIT_VERSION};
      wget -O - https://github.com/git/git/archive/v${version}.tar.gz && tar xvf -;
    done
  - hash -r
  - popd
install:
  - bundle install
script:
  - bundle exec rake install
  - bundle exec rake spec
evn:
  - GIT_VERSIONS="1.8.4 1.8.3 1.8.2 1.8.1 1.8.0 1.7.0 1.6.0 1.5.0 1.4.0 1.3.0"


