language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.9.1
  - 1.8.7
  - 1.8.6
install:
  - for version in ${GIT_VERSIONS}; do
      wget -O - https://github.com/git/git/archive/v${version}.tar.gz && tar xvf -;
    done
  - ls
evn:
  - GIT_VERSIONS="1.8.4 1.8.3 1.8.2 1.8.1 1.8.0 1.7.0 1.6.0 1.5.0 1.4.0 1.3.0"


