language: ruby
rvm:
  - 2.0.0
  - 1.9.3
before_install:
  - git config --global user.email "dummy@localhost"
  - git config --global user.name "This Is Dummy"
install:
  - bundle install
  - bundle exec rake install
script:
  - bundle exec rake spec

