sites:
  test_dummy:
    driver:   dummy
    user:     dummy
    password: dummy
  test_11111:
    driver:   codeforces
    user:     dummy
    password: dummy
  test_22222:
    driver:   aizu_online_judge
    user:     dummy
    password: dummy
  test_33333:
    driver:   uva_online_judge
    user:     dummy
    password: dummy
